version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        container_name: symfony-php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        expose:
            - "9000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: symfony-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - /root/archivos/tickets/db_data:/var/lib/mysql        

    symfony-nginx:
        image: nginx:latest
        container_name: symfony-nginx
        volumes:
            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
        ports:
            - "81:80"
            - "1443:443"
        environment:
            - VIRTUAL_HOST=${APP_DOMAIN}
